name: Deploy Application

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  id-token: write
  contents: read

env:
  AZURE_CONTAINER_REGISTRY: alocpath

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          lfs: true

      # Azure login
      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.ARM_CLIENT_ID }}
          tenant-id: ${{ secrets.ARM_TENANT_ID }}
          subscription-id: ${{ secrets.ARM_SUBSCRIPTION_ID }}

      - name: ACR Login
        run: |
          az acr login -n ${{ env.AZURE_CONTAINER_REGISTRY }}

      # Build and Push Docker Image
      -   name: Build and Push Docker Image
          run: |
            docker build -t ${{ env.AZURE_CONTAINER_REGISTRY }}.azurecr.io/oc-student-sentiment:latest .
            docker push ${{ env.AZURE_CONTAINER_REGISTRY }}.azurecr.io/oc-student-sentiment:latest
