name: Deploy Application

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
            # Checkout the code
            - name: Checkout code
              uses: actions/checkout@v3

            # Setup Terraform
            - name: Setup Terraform
              uses: hashicorp/setup-terraform@v2
              with:
                  terraform_version: 1.5.0


            # Export Azure Environment Variables
            -   name: Export Azure Credentials
                env:
                    ARM_CLIENT_ID: ${{ fromJson(secrets.AZURE_CREDENTIALS).clientId }}
                    ARM_CLIENT_SECRET: ${{ fromJson(secrets.AZURE_CREDENTIALS).clientSecret }}
                    ARM_SUBSCRIPTION_ID: ${{ fromJson(secrets.AZURE_CREDENTIALS).subscriptionId }}
                    ARM_TENANT_ID: ${{ fromJson(secrets.AZURE_CREDENTIALS).tenantId }}
                run: |
                    echo "Azure environment variables set."

            # Clean Terraform Cache
            -   name: Clean Terraform Cache
                run: rm -rf terraform/.terraform

            # Initialize Terraform
            -   name: Initialize Terraform
                run: terraform -chdir=terraform init

            # Check Terraform Formatting
            -   name: Check Terraform Formatting
                run: terraform -chdir=terraform fmt -check

            # Validate Terraform Configuration
            -   name: Validate Terraform Configuration
                run: terraform -chdir=terraform validate

            # Terraform Plan
            -   name: Terraform Plan
                run: terraform -chdir=terraform plan

            # Terraform Apply
            -   name: Terraform Apply
                id: apply
                run: terraform -chdir=terraform apply -auto-approve

            # Login to Azure Container Registry
            -   name: Azure Login
                uses: azure/login@v1
                with:
                    creds: ${{ secrets.AZURE_CREDENTIALS }}

            # Build and Push Docker Image
            -   name: Build and Push Docker Image
                run: |
                    docker build -t alocpath.azurecr.io/oc-student-sentiment:latest .
                    docker push alocpath.azurecr.io/oc-student-sentiment:latest

            # Output App URL
            -   name: Output App URL
                run: |
                    echo "App URL: $(terraform -chdir=terraform output -raw app_service_url)"

