name: Deploy Application

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
    ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
    ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
    ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
    ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Azure Login
      - name: Azure Login
        uses: azure/login@v1

      # Docker login
      - name: Docker login
        run: |
          az acr login --name alocpath

      # Build and Push Docker Image
      - name: Build and Push Docker Image
        run: |
          docker build -t alocpath.azurecr.io/oc-student-sentiment:latest .
          docker push alocpath.azurecr.io/oc-student-sentiment:latest

      # Output App URL
      - name: Output App URL
        run: |
          echo "App URL: $(terraform -chdir=terraform output -raw app_service_url)"
