name: Deploy Application

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

env:
    ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
    ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
    ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
    ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}

jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
            # Checkout the code
            -   name: Checkout code
                uses: actions/checkout@v3

            # Setup Terraform
            -   name: Setup Terraform
                uses: hashicorp/setup-terraform@v2
                with:
                    terraform_version: 1.5.0

            # Terraform Init
            -   name: Initialize Terraform
                run: terraform init

            # Terraform Format Check
            -   name: Format and validate Terraform
                run: |
                    terraform fmt -check
                    terraform validate

            # Terraform Plan
            -   name: Terraform Plan
                run: terraform plan

            # Terraform Apply
            -   name: Terraform Apply
                id: apply
                run: terraform apply -auto-approve

            # Login to Azure Container Registry
            -   name: Azure Login
                uses: azure/login@v1
                with:
                    creds: ${{ secrets.AZURE_CREDENTIALS }}

            # Build and Push Docker Image
            -   name: Build and Push Docker Image
                run: |
                    docker build -t alocpath.azurecr.io/oc-student-sentiment:latest .
                    docker push alocpath.azurecr.io/oc-student-sentiment:latest

            # Output App URL
            -   name: Output App URL
                run: |
                    echo "App URL: $(terraform output -raw app_service_url)"
